name: dart_bug_demo
description: A web app that uses AngularDart 
# version: 1.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  ngdart: 7.1.1

dev_dependencies:
  build_runner: 2.3.3   
  build_web_compilers: 3.2.6
  